[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "AIRTABLE_RSVP_TABLE,AIRTABLE_REGISTRY_TABLE,AIRTABLE_INVITES_TABLE"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
